spring:
  datasource:
    url: jdbc:mysql://localhost:3306/transinfo?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      max-active: 100
  task:
    scheduling:
      pool:
        size: 5

mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      table-prefix:
      id-type: auto

jasypt:
  encryptor:
    password: mySecretKey

logging:
  level:
     org.springframework.web: INFO
     com.liu.javaproject: INFO


# 文件访问路径前缀
fileAccessUrlPrefix: http://192.168.0.11:8088/resources

# 商品图片访问路径前缀
goodsImgAccessUrlPrefix: http://122.112.143.244/assets/

# 文件存储路径前缀
#localPathPrefix: D:\assets
localPathPrefix: /home/assets

file:
  # 文件访问路径前缀
  accessUrlPrefix: http://192.168.0.11:8088/resources
  # 文件存储路径前缀
  localPathPrefix: /home/assets

#外部接口调用路径
url:
  cOrdersUrl: http://localhost:8070/cOrders